# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:20
from __future__ import unicode_literals

import autoslug.fields
import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.CharField(max_length=24, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user should be treated as active. Unselect this instead of\n         deleting accounts.', verbose_name='active')),
                ('department', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('session', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('profile_image', core.fields.TimestampImageField(blank=True, null=True, upload_to='profiles/pic')),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (7, 'ACTIVE'), (1, 'PENDING'), (2, 'DENIED'), (3, 'COMPLETED'), (4, 'ARCHIVED'), (5, 'HIDDEN'), (6, 'REMOVED')], default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'persons',
                'verbose_name': 'person',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (7, 'ACTIVE'), (1, 'PENDING'), (2, 'DENIED'), (3, 'COMPLETED'), (4, 'ARCHIVED'), (5, 'HIDDEN'), (6, 'REMOVED')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Assignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'assignments',
                'verbose_name': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('deadline', models.DateField()),
                ('alias', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('container_name', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('container_tag', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (7, 'ACTIVE'), (1, 'PENDING'), (2, 'DENIED'), (3, 'COMPLETED'), (4, 'ARCHIVED'), (5, 'HIDDEN'), (6, 'REMOVED')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Assignment')),
                ('clone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.StudentAssignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'student_assignment',
                'verbose_name': 'student_assignment',
            },
        ),
    ]
