# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_group',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'TEACHER'), (2, 'STUDENT')], default=0),
        ),
    ]
