# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_person_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name': 'student_assignment', 'verbose_name_plural': 'student_assignments'},
        ),
    ]
