# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171116_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name': 'studentAssignment', 'verbose_name_plural': 'studentAssignments'},
        ),
    ]
