# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171116_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name': 'student assignment', 'verbose_name_plural': 'student assignments'},
        ),
    ]
