# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171116_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='alias',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
