# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171118_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignment_session', to='core.Session'),
        ),
        migrations.AlterField(
            model_name='person',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Session'),
        ),
    ]
