# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171120_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='creation_date',
        ),
    ]
