# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_studentassignment_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='github_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='container_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='container_tag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
