# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171127_2014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentassignment',
            unique_together=set([('student', 'assignment')]),
        ),
    ]
